--- #Service-Manifests
metadata:
  app: 
selector:
  app: 
port:

--- #Statefulset-Manifests
metadata:
  labels: spc
minReadySeconds: 5
replicas: 2
matchLabels:
  labels: spc
template:
  labels: spc
containers:
  name: spc
  image: 
ports:
  containerPort:
resources:
  limits:
    memory:
    cpu:  
  requests:
    memory:
    cpu:
volumes:
  name:
  mountPath:
serviceName:
volumeClaimTemplates:
  name:
  accessModes: -ReadWriteOnce
  storageClassName:
  storage: 

--- #books-db-svc
selector:
  app: 

--- #books-db-stsflst
replicas:
selector:
  app: 
template:
  app:
containers:
  name:
  image:
  tag:
resources:
  requests:
  limits:
  
--- #user-db-svc
selector:
  app: 


--- #user-db-stsflst
replicas:
selector:
  app: 
template:
  app:
containers:
  name:
  image:
  tag:
resources:
  requests:
  limits:

--- #bksdb-sec
data:
  MYSQL_ROOT_PASSWORD: rootpassword 
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQK
  MYSQL_DB: YmtzZGI=

--- #usrdb-sec
data:
  MYSQL_ROOT_PASSWORD: rootpassword  
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQK
  MYSQL_DB: dXNyZGI=
  
    
  
  





