---
apiVersion: v1
kind: Secret 
metadata:
  name:  bksdb-sec
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.data.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.data.MYSQL_PASSWORD }}
  MYSQL_DB: {{ .Values.data.MYSQL_DB }}

---
apiVersion: v1
kind: Secret 
metadata:
  name: usrdb-sec 
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.data.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.data.MYSQL_PASSWORD }}
  MYSQL_DB: {{ .Values.data.MYSQL_DB }}

---
apiVersion: v1
kind: Secret
metadata:
  name: bksdb-svc-sec
data:
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
  DATABASE_URL: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQGJrc2RiLTAuYmtzZGItc3ZjOjMzMDYvYmtzZGI=

---
apiVersion: v1
kind: Secret
metadata:
  name: usrdb-svc-sec
data:
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
  DATABASE_URL: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQHVzcmRiLTAudXNyZGItc3ZjOjMzMDYvdXNyZGI=

  
