---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Values.metadata.app }}
spec:
  type: LoadBalancer
  LoadBalancer: None
  selector:
    app:  {{ .Values.selector.app }}
  ports:
  - port: {{ .Values.port }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-spc
  labels:
    app: {{ .Values.metadata.labels }}
spec:
  minReadySeconds:  {{ .Values.minReadySeconds }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      labels:
        app: {{ .Values.matchLabels.labels }}
    template:
      metadata:
        labels:
         app: {{ .Values.template.labels }}
      spec:
        containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
          ports:
          - containerPort: {{ .Values.ports.containerPort }}
          resources:
            limits: {{ .Values.resources.limits | toYaml | nindent 14 }}
            requests: {{ .Values.resources.rquests | toYaml | nindent 14 }}
        volumes:
          name: {{ .Values.volumes.name }}
          mountPath: {{ .Values.volumes.mountPath }}
  serviceName: {{ .Values.servicename }}
  volumeClaimTemplates:
    metadata:
      name: {{ .Values.volumeClaimTemplates.name }}
    spec:
      accessModes: {{ .Values.volumeClaimTemplates.accessModes | toYaml | nindent 8 }}
      storageClassName: {{ .Values.volumeClaimTemplates.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.volumeClaimTemplates.storage }}
