---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Values.selector.app }}
  ports:
    - port: 3306
      targetPort: 3306


---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ .Release.Name }}-sts
spec:
  minReadySeconds: 5
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  serviceName: usrdb-svc
  template:
    metadata:
      labels:
        app: {{ .Values.template.app }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          ports:
          - containerPort: 3306
          envFrom:
            - secretRef:
                name: usrdb-sec
          env:
           - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DB
              value: usrdb
          resources:
            requests: {{ .Values.resources.requests }}
            limits: {{ .Values.resources.limits }}
          volumeMounts:
            - name: volume 
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
  - metadata:
      name: volume 
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: managed
      resources:
        requests: 
          storage: 5Gi

